language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t dreamsctv/react-portfolio -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true dreamsctv/react-portfolio npm run test

after_success:
  - docker build -t dreamsctv/portfolio-frontend ./frontend
  - docker build -t dreamsctv/portfolio-backend ./backend
  - docker build -t dreamsctv/portfolio-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dreamsctv/portfolio-frontend
  - docker push dreamsctv/portfolio-backend
  - docker push dreamsctv/portfolio-nginx

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'portfolio'
  env: 'Portfolio-env'
  bucker_name: elasticbeanstalk-us-east-2-856304157938
  bucker_path: 'portfolio'
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
